### ISSUE TITLE
409 Already Exists results in unsynchronized image

### ISSUE THREAD

**Issue by andyt** [cloudinary/cloudinary_magento#11]
If an image already exists in Cloudinary, the returned 409 AlreadyExists error should be caught and the image tagged as synchronized.

**Comment by taragano** [comment]
Hi @andyt,

Can you please share some more information regarding the flow and use-case?
Did you re-upload an image, trying to update (overwrite) an existing one?
Was this error returned during a single image upload or the bulk migration?

**Comment by andyt** [comment]
This is during migration of images to Cloudinary using the Magento plugin. My database was reimported without the cloudinary migration table data, so I restarted the migration. Images which were re-uploaded but existed on Cloudinary already were blocking the migration, as they were recorded as errors, whereas in fact they simply need to be tagged as synchronized.

I've forked the plugin and fixed the problem (and am now fully synchronized). However, I am struggling to run the tests due to composer dependency issues.

**Comment by grantkemp** [comment]
@andyt can you share your code?

**Comment by andyt** [comment]
https://github.com/cloudinary/cloudinary_magento/pull/12

**Comment by idobarnoam** [comment]
Hi @andyt 
I'm closing this thread since you are no longer having this issue. And there is an outstanding pull request.
Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
