### ISSUE TITLE
Cannot save the Cloudinary configuration

### ISSUE THREAD

**Issue by maxacarvalho** [cloudinary/cloudinary_magento#46]
I notice that when trying to save the configuration or uploading an image the method `\Cloudinary_Cloudinary_Model_System_Config_Free::validateImageUrl` is called.

The method above is making a call to the *sample* image, which returns a 404 and with the method above throws a `throw new Mage_Core_Exception($this->formatError($response));` which makes impossible to save the configuration.

**Comment by idobarnoam** [comment]
Hi @maxacarvalho Could you share the Magento version you are using and the module version?

Also what is the error that you are seeing?

**Comment by maaxxicarvalho** [comment]
Hi @idobarnoam 
Let me give you a bit of context.

I have three environments **Production**, **Staging** and **Development**.  
The idea is that all three environments share the same Cloudinary account so the resources are always available and up to date across all of them.

The above said. When I was trying to setup the Cloudinary Magento plugin on my local (development environment I got an error saying `Incorrect custom transform ...`.  
And I was simply inputting the Cloudinary **Environment variable**.

After some investigation I checked that the class `app/code/community/Cloudinary/Cloudinary/Model/System/Config/Free.php` calls a method `validateImageUrl($url)` which attempts to get the `sampleImage` (`$this->validateImageUrl($this->sampleImageUrl($transform));`).

For this is a bit weird since the first thing I do when I start a Cloudinary account is to delete the sample image since I don't want things that I'm not using polluting the Media library.  
But, since I saw that this weird validation was happening I restored the sample image. Still, the method was calling and returning a `404` saying that the image is not there. But it is there.

The only solution I found was to comment out the line `app/code/community/Cloudinary/Cloudinary/Model/System/Config/Free.php:41`, save the configuration and then uncomment the line.

**Comment by idobarnoam** [comment]
Thanks @maxacarvalho This is very helpful.

In order for us to pinpoint this, could you share the version number of both the Cloudinary module you are using and the Magento environment?

**Comment by maaxxicarvalho** [comment]
Hi again @idobarnoam 
The Magento is at version `1.9.3.8`
The Cloudinary extension is at version `2.8.2`

**Comment by idobarnoam** [comment]
Thanks, @maxacarvalho would it be possible to [update](https://github.com/cloudinary/cloudinary_magento) the Cloudinary module to the latest one which is 2.9.6 and see if that helps?

**Comment by maaxxicarvalho** [comment]
I will do that later today @idobarnoam.
It's weird that I'm so many versions behind, I just installed the extension one month ago, downloaded from the Magento market place.

Also, I just downloaded the extension from the releases page and the `app/code/community/Cloudinary/Cloudinary/etc/config.xml` file says `2.9.5` instead of `2.9.6`

**Comment by maaxxicarvalho** [comment]
Hi @idobarnoam 
Just to let you know that the configuration is being saved properly.

But now I have another issue, the method `code/community/Cloudinary/Cloudinary/Model/Catalog/Product/Media.php:37` is throwing an exception
```php
There is one error message from magento server

Argument 1 passed to Cloudinary_Cloudinary_Model_Catalog_Product_Media::_getRemovedImages() must be of the type array, null given, called in code/community/Cloudinary/Cloudinary/Model/Catalog/Product/Media.php on line 39
```

This is happening because the `code/community/Cloudinary/Cloudinary/Model/Catalog/Product/Media.php:42` method expects an array but the `$product->getMediaGallery()` could return `null`

**Comment by idobarnoam** [comment]
@maaxxicarvalho Thanks for letting us know.

Is the nodule currently working properly when you get this error?

**Comment by maaxxicarvalho** [comment]
Hi @idobarnoam 

It throws an exception when I try to create or update a product using the Magento API.

The problem happens because the Magento Product `media_gallery` can return `null`.
Since some of the methods of the Cloudinary plugin expects an `array` a fatal error occurs.

For example, the class `app/code/community/Cloudinary/Cloudinary/Model/Catalog/Product/Media.php` method `newImagesForProduct`

That's how it is
```php
public function newImagesForProduct(Mage_Catalog_Model_Product $product)
    {
        $this->_setNewImages($product->getData('media_gallery'));
        return $this->_getNewImages($product);
    }
```

and that's how I solved the issue
```php
public function newImagesForProduct(Mage_Catalog_Model_Product $product)
    {
        $mediaGallery = $product->getData('media_gallery') ?? [];
        $this->_setNewImages($mediaGallery);
        return $this->_getNewImages($product);
    }
```

**Comment by idobarnoam** [comment]
@maaxxicarvalho Thanks for sharing your solution!

I'll take this internally with our dev team and see how we can address the issue internally.

**Comment by MageSuper** [comment]
@idobarnoam @maaxxicarvalho Yep, you were right, it might return null and when it does it break the configurable product quick create functionality altogether.

Please consider the following #49

**Comment by eyalktCloudinary** [comment]
Closing due to time elapsed.
